/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.inicio;
import java.awt.HeadlessException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;

/**
 *
 * @author Sebas
 */
public class index extends javax.swing.JFrame {

    /**
     * Creates new form index
     */
    public index() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JPanel();
        TituloP = new javax.swing.JLabel();
        TituloP1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        año = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        dia = new javax.swing.JTextField();
        mes = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setBackground(new java.awt.Color(229, 229, 229));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TituloP.setFont(new java.awt.Font("Limelight", 0, 36)); // NOI18N
        TituloP.setForeground(java.awt.Color.white);
        TituloP.setText("PROYECTO JAVA");
        background.add(TituloP, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, -1, -1));

        TituloP1.setFont(new java.awt.Font("Limelight", 0, 36)); // NOI18N
        TituloP1.setText("Proyecto Unidad Cuatro");
        background.add(TituloP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 77, 0, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/lateral.jpg"))); // NOI18N
        background.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 320, 330));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/imagenes/principal.jpg"))); // NOI18N
        background.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 190));

        jLabel3.setFont(new java.awt.Font("Limelight", 0, 24)); // NOI18N
        jLabel3.setForeground(java.awt.Color.darkGray);
        jLabel3.setText("COMO SER VIVIENTE?");
        background.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, 420, 30));

        jLabel4.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        jLabel4.setForeground(java.awt.Color.gray);
        jLabel4.setText("DIGITE LA FECHA DE SU NACIMIENTO");
        background.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 290, 350, -1));

        jLabel5.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        jLabel5.setForeground(java.awt.Color.gray);
        background.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 280, -1, -1));

        jLabel6.setFont(new java.awt.Font("Limelight", 0, 24)); // NOI18N
        jLabel6.setForeground(java.awt.Color.darkGray);
        jLabel6.setText("AÑO");
        background.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 330, 60, -1));

        año.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        año.setForeground(java.awt.Color.gray);
        año.setBorder(new javax.swing.border.LineBorder(java.awt.Color.lightGray, 5, true));
        año.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añoActionPerformed(evt);
            }
        });
        background.add(año, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 360, 80, 40));

        jButton1.setFont(new java.awt.Font("Limelight", 0, 18)); // NOI18N
        jButton1.setText("Enter");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        background.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 440, 110, 50));

        jLabel7.setFont(new java.awt.Font("Limelight", 0, 24)); // NOI18N
        jLabel7.setForeground(java.awt.Color.darkGray);
        background.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 430, -1, -1));

        dia.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        dia.setForeground(java.awt.Color.gray);
        dia.setBorder(new javax.swing.border.LineBorder(java.awt.Color.lightGray, 5, true));
        dia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diaActionPerformed(evt);
            }
        });
        background.add(dia, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 360, 80, 40));

        mes.setFont(new java.awt.Font("Roboto Condensed", 0, 18)); // NOI18N
        mes.setForeground(java.awt.Color.gray);
        mes.setBorder(new javax.swing.border.LineBorder(java.awt.Color.lightGray, 5, true));
        mes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesActionPerformed(evt);
            }
        });
        background.add(mes, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 360, 80, 40));

        jLabel8.setFont(new java.awt.Font("Limelight", 0, 24)); // NOI18N
        jLabel8.setForeground(java.awt.Color.darkGray);
        jLabel8.setText("MES");
        background.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, 60, -1));

        jLabel9.setFont(new java.awt.Font("Limelight", 0, 24)); // NOI18N
        jLabel9.setForeground(java.awt.Color.darkGray);
        jLabel9.setText("DIA");
        background.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, -1, -1));

        jLabel10.setFont(new java.awt.Font("Limelight", 0, 24)); // NOI18N
        jLabel10.setForeground(java.awt.Color.darkGray);
        jLabel10.setText("¿DESEA CONOCER SUS DIAS");
        background.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 220, 390, 30));

        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 550));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void añoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_añoActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked

        int diaU = Integer.parseInt(dia.getText());
        int mesU = Integer.parseInt(mes.getText());
        int añoU = Integer.parseInt(año.getText());
        
        if(diaU > 31){
            JOptionPane.showMessageDialog(null, "Recuerda que los meses solo tienen 31 dias maximo");
            if(mesU > 12){
                JOptionPane.showMessageDialog(null, "Recuerda que solo hay 12 meses");
                if(añoU < 0){
                    JOptionPane.showMessageDialog(null, "No se aceptan años negativos");
                }
            }
        }else if(mesU > 12){
            JOptionPane.showMessageDialog(null, "Recuerda que solo hay 12 meses"); 
            if(añoU < 0){
                JOptionPane.showMessageDialog(null, "No se aceptan años negativos");
            }
        }else if(añoU < 0){
            JOptionPane.showMessageDialog(null, "No se aceptan años negativos");
        }else{
            try{
                int resultado = dias(diaU,mesU,añoU);
                if(resultado > 0){
                    if(resultado >= 37000){
                        JOptionPane.showMessageDialog(null, "Tu has vivido " + resultado + " dias");
                        JOptionPane.showMessageDialog(null, "Realmente las personas no viven tanto. Revisa tu año de nacimiento");
                    }else{
                        JOptionPane.showMessageDialog(null, "Tu has vivido " + resultado + " dias");
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "Al parecer aun no has nacido, ¿Que haces aqui?");
                }
            }catch(HeadlessException InputMismatchException){
                JOptionPane.showMessageDialog(null, "Recuerda que tu año de nacimiento es un numero");
            }
        }
                
    }//GEN-LAST:event_jButton1MouseClicked

    private void diaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_diaActionPerformed

    private void mesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    static int dias(int diaU, int mesU, int año){                                                                             //Dias vividos

        int dia;
        int mes;
        int vivido;
        int menos = diaU + (mesU*30);

        Calendar fecha = new GregorianCalendar();
        mes = fecha.get(Calendar.MONTH);
        dia = fecha.get(Calendar.DATE);

        vivido = ((((2022-año)*365) + ((mes+1)*30) + dia)) - menos;

       return vivido;

    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TituloP;
    private javax.swing.JLabel TituloP1;
    private javax.swing.JTextField año;
    private javax.swing.JPanel background;
    private javax.swing.JTextField dia;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField mes;
    // End of variables declaration//GEN-END:variables
}
